services:
  ohconsol_db:
    image: mariadb:11
    container_name: ohconsol_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example_root_pw
      MYSQL_DATABASE: fileapp
      MYSQL_USER: fileapp
      MYSQL_PASSWORD: fileapp_pw
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - host

  ohconsol_web:
    image: 2jdock/2jpub:ohconsol
    container_name: ohconsol_web
    depends_on:
      - ohconsol_db
    ports:
      - "8080:80"        # Access webapp on host:8080
      - "8081:8081"     # required for serial websocket
      - "69:69/udp"    # TFTP UDP port forwarded to host
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0" # change host side to your USB device mapping
    privileged: true   # required for serial access
    environment:
      DB_HOST: ohconsol_db
      DB_NAME: fileapp
      DB_USER: fileapp
      DB_PASS: fileapp_pw
    volumes:
      - uploads:/var/www/html/uploads
      - tftp:/mnt/tftp
    restart: unless-stopped
    networks:
      - host
    cap_add:
      - NET_BIND_SERVICE

volumes:
  db_data:
  uploads:
  tftp:

networks:
  host:
    driver: bridge
